imu:
  frame_id: "fcu"
  topic: "mavros/imu/data"
  gravity: 9.8
  providesOrientation: false # requires 9-DOF IMU
  deskew: false # use imu to deskew cloud (requires 9-DOF IMU)
  interpolateOrientation: # linear interpolation between scan matching result and IMU orientation (requires 9-DOF IMU)
    enable: false
    weight: 0.01
  noise:
    linAcc: 0.006
    angVel: 0.00018665
    linAccBias: 1
    angVelBias: 0.1
